language: minimal
sudo: false
dist: trusty
git:
  submodules: false
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  timeout: 300
addons:
  apt:
    packages:
    - python
    - python-numpy
    - libgmp-dev
    - python-sphinx
stages:
- deps
- compiler
- tests
- deploy
before_install:
- "./.travis-setup.sh"
- export PATH=$HOME/.local/bin:$PATH
jobs:
  include:
  - stage: deps
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &1
    - stack build --fast alex happy
    - stack --no-terminal test --fast --only-dependencies -j 3
  - stage: deps
    env: BUILD=stack STACK_YAML=stack-lts-10.0.yaml
    script: *1
  - stage: deps
    env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml
    script: *1
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &2
    - travis_wait stack --no-terminal test -j 1 --fast
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack-lts-10.0.yaml
    script: *2
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml
    script: *2
  - stage: tests
    env: BUILD=stack STACK_YAML=stack.yaml
    script:
    - stack install
    - futhark-test --nobuffer tests examples
    - "(cd pkgtests; ./test.sh)"
    - stack install hlint --fast
    - tools/style-check.sh src
  - stage: deploy
    env: BUILD=stack STACK_YAML=stack.yaml
    if: tag =~ ^v
    script:
    - export VERSION=$(echo "$TRAVIS_TAG" | sed 's/^v//')
    - export VERSION=$(echo v0.0.0 | sed 's/^v//')
    - export TARBALL=futhark-$VERSION.tar.xz
    - tools/release/binary-tarball.sh . "-$VERSION"
    deploy:
      provider: releases
      api_key:
        secure: OHk9iTQjnPGjw1/sLvePHVmUBV8S5Tq32xUiz4GvkoFVA9S5s8BP8HPiOQinZGVU7YVqn4FWQaxg1bHkbNSSHbQP6dmkhLme0HAVPxt/ravGd0Hb+T4ioudT63G05fQ2r8Yk1Dt+aS7v07uI5PGsQENIdmNR8ns98YHOwZf+haQ=
      file_glob: true
      file: "${TARBALL}"
      on:
        repo: diku-dk/futhark
        tags: true
      skip_cleanup: true
