language: minimal

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.stack

# We test against different Stackage snapshots.
matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-7.24.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml

addons:
  apt:
    sources:
      - sourceline: 'ppa:adrozdoff/emacs'
    packages:
    - hlint
    - python
    - python-numpy
    - libgmp-dev
    - emacs25

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh

install:
 - stack build --fast alex happy
 - stack --no-terminal test --fast --only-dependencies -j 3

script:
 - stack --no-terminal test -j 3
 - stack install

 # Run integration test suite.
 - if [ "$STACK_YAML" = stack.yaml ]; then futhark-test --nobuffer tests examples; fi

 # Numpy is broken on Travis in a weird way I can't reproduce anywhere else.
 # - futhark-test tests examples --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.

 # Check for style issues.
 - if [ "$STACK_YAML" = stack.yaml ]; then stack install hlint --fast && tools/style-check.sh src;

 # Check the automatic indentation feature of the futhark-mode.el
 # Emacs editing mode.
 - if [ "$STACK_YAML" = stack.yaml ]; then cd tools && ./futhark-mode.el-corpus-test.sh; fi

# EOF
