language: minimal
dist: trusty
git:
  submodules: false
  depth: 5
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  timeout: 1000
addons:
  apt:
    packages:
    - python
    - python-numpy
    - libgmp-dev
    - python-sphinx
    - rsync
stages:
- deps
- compiler
- tests
- deploy
before_install:
- "./.travis-setup.sh"
- export PATH=$HOME/.local/bin:$PATH
jobs:
  include:
  - stage: deps
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &1
    - stack build alex happy
    - stack --no-terminal test --only-dependencies -j 3
  - stage: deps
    env: BUILD=stack STACK_YAML=stack-lts-12.11.yaml
    script: *1
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &2
    - stack --no-terminal test -j 3
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack-lts-12.11.yaml
    script: *2
  - stage: style
    env: BUILD=stack STACK_YAML=stack-lts-12.11.yaml
    script:
    - stack install hlint --fast
    - tools/style-check.sh src
  - stage: tests
    env: BUILD=stack STACK_YAML=stack.yaml
    script:
    - stack install
    - futhark test --no-terminal tests examples --no-tuning
    - "(cd pkgtests; ./test.sh)"
  - stage: deploy
    env: BUILD=stack STACK_YAML=stack.yaml
    if: tag =~ ^v
    before_install:
    - openssl aes-256-cbc -K $encrypted_0f71ac12d865_key -iv $encrypted_0f71ac12d865_iv -in .travis_rsa.enc -out /tmp/travis_rsa -d
    - "./.travis-setup.sh"
    - export PATH=$HOME/.local/bin:$PATH
    script:
    - export VERSION=$(echo "$TRAVIS_TAG" | sed 's/^v//')
    - export SLUG=$VERSION-linux-x86_64
    - export TARBALL=futhark-$SLUG.tar.xz
    - tools/release/binary-tarball.sh . "-$SLUG"
    before_deploy:
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_rsa
    - ssh-add /tmp/travis_rsa
    - echo -e "Host sigkill.dk\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    deploy:
      # Copy tarball to GitHub releases.
      - provider: releases
        api_key:
          secure: OHk9iTQjnPGjw1/sLvePHVmUBV8S5Tq32xUiz4GvkoFVA9S5s8BP8HPiOQinZGVU7YVqn4FWQaxg1bHkbNSSHbQP6dmkhLme0HAVPxt/ravGd0Hb+T4ioudT63G05fQ2r8Yk1Dt+aS7v07uI5PGsQENIdmNR8ns98YHOwZf+haQ=
        file_glob: true
        file: "${TARBALL}"
        on:
          repo: diku-dk/futhark
          tags: true
        skip_cleanup: true

      # Copy tarball to our own webserver.
      - provider: script
        script: rsync -r --delete-after $TRAVIS_BUILD_DIR/$TARBALL futhark@sigkill.dk:/var/www/htdocs/futhark-lang.org/releases/
        on:
          repo: diku-dk/futhark
          tags: true
        skip_cleanup: true
